In [4]:
# load in the csv file/Data
import pandas as pd
df = pd.read_csv(r'books_full_dataset.csv')
df

,Title,Price (£),Rating,Availability
0,A Light in the Attic,Â51.77,Three,In stock
1,Tipping the Velvet,Â53.74,One,In stock
2,Soumission,Â50.10,One,In stock
3,Sharp Objects,Â47.82,Four,In stock
4,Sapiens: A Brief History of Humankind,Â54.23,Five,In stock
...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â55.53,One,In stock
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â57.06,Four,In stock
997,A Spy's Devotion (The Regency Spies of London #1),Â16.97,Five,In stock
998,1st to Die (Women's Murder Club #1),Â53.98,One,In stock
999,"1,000 Places to See Before You Die",Â26.08,Five,In stock

In [5]:
df.shape

(1000, 4)

In [6]:
df.head()

                                   Title Price (£) Rating Availability
0                   A Light in the Attic    Â51.77  Three     In stock
1                     Tipping the Velvet    Â53.74    One     In stock
2                             Soumission    Â50.10    One     In stock
3                          Sharp Objects    Â47.82   Four     In stock
4  Sapiens: A Brief History of Humankind    Â54.23   Five     In stock

In [7]:
df.tail()

,Title,Price (£),Rating,Availability
995,Alice in Wonderland (Alice's Adventures in Won...,Â55.53,One,In stock
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â57.06,Four,In stock
997,A Spy's Devotion (The Regency Spies of London #1),Â16.97,Five,In stock
998,1st to Die (Women's Murder Club #1),Â53.98,One,In stock
999,"1,000 Places to See Before You Die",Â26.08,Five,In stock

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   object
 1   Price (£)     1000 non-null   object
 2   Rating        1000 non-null   object
 3   Availability  1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

In [9]:
# Display all column names
# Useful to verify that the dataset structure is correct

df.columns

Index(['Title', 'Price (£)', 'Rating', 'Availability'], dtype='object')

In [10]:
# Check for missing (null) values in each column
# True values indicate missing data

df.isnull().sum()

Title           0
Price (£)       0
Rating          0
Availability    0
dtype: int64

In [11]:
# Check for duplicate rows in the dataset
# Returns the total number of duplicated records

df.duplicated().sum()

np.int64(0)

In [12]:
# Check for rows where all values are empty or missing
# This helps detect completely blank records

empty_rows = df[df.isnull().all(axis=1)]

empty_rows
# Count total empty rows

empty_rows.shape[0]

0

In [13]:
# Display percentage of missing values per column
# Helps understand how serious the missing data problem is

missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent

Title           0.0
Price (£)       0.0
Rating          0.0
Availability    0.0
dtype: float64

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         1000 non-null   object
 1   Price (£)     1000 non-null   object
 2   Rating        1000 non-null   object
 3   Availability  1000 non-null   object
dtypes: object(4)
memory usage: 31.4+ KB

In [15]:
# #After scraping, the next important step is data type cleaning and transformation.
# Right now:

# Price is stored as text (string)

# Rating is also text

# Analysis and visualization require numeric values

# fixing that and also converting the price from Pounds (£) to Nigerian Naira (₦).


# Check the data type of each column
# This helps us identify which columns need conversion

df.dtypes

Title           object
Price (£)       object
Rating          object
Availability    object
dtype: object

In [16]:

# -------------------------------
# STEP 1: Clean and convert Price (£)
# -------------------------------

# 1️⃣ Remove any non-numeric characters (like 'Â' or '£') using regex
# 2️⃣ Convert the cleaned string to float so we can do numeric operations
df["Price (£)"] = df["Price (£)"].replace(r'[^0-9.]', '', regex=True).astype(float)

# 3️⃣ Optional: convert to Naira using a fixed exchange rate
exchange_rate = 2000  # £1 ≈ ₦2000
df["Price (₦)"] = df["Price (£)"] * exchange_rate

# -------------------------------
# STEP 2: Convert Rating text to numeric
# -------------------------------

# 1️⃣ Strip whitespace from Rating column (in case of extra spaces)
df["Rating"] = df["Rating"].astype(str).str.strip()

# 2️⃣ Map textual ratings to numeric values
# "One" → 1, "Two" → 2, ..., "Five" → 5
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["Rating"] = df["Rating"].map(rating_map)

# 3️⃣ Handle any missing ratings (e.g., if some books had no rating)
# Fill missing values with 0 to indicate "no rating"
df["Rating"] = df["Rating"].fillna(0).astype(int)

# -------------------------------
# STEP 3: Quick check
# -------------------------------
print(df.head(10))

                                               Title  Price (£)  Rating  \
0                               A Light in the Attic      51.77       3
1                                 Tipping the Velvet      53.74       1
2                                         Soumission      50.10       1
3                                      Sharp Objects      47.82       4
4              Sapiens: A Brief History of Humankind      54.23       5
5                                    The Requiem Red      22.65       1
6  The Dirty Little Secrets of Getting Your Dream...      33.34       4
7  The Coming Woman: A Novel Based on the Life of...      17.93       3
8  The Boys in the Boat: Nine Americans and Their...      22.60       4
9                                    The Black Maria      52.15       1

  Availability  Price (₦)
0     In stock   103540.0
1     In stock   107480.0
2     In stock   100200.0
3     In stock    95640.0
4     In stock   108460.0
5     In stock    45300.0
6     In stock    66680.0
7     In stock    35860.0
8     In stock    45200.0
9     In stock   104300.0

In [18]:
# Ensure correct types
df["Price (£)"] = df["Price (£)"].astype(float)
df["Price (₦)"] = df["Price (₦)"].astype(float)
df["Rating"] = df["Rating"].astype(int)
df["Title"] = df["Title"].astype(str)
df["Availability"] = df["Availability"].astype(str)
df

,Title,Price (£),Rating,Availability,Price (₦)
0,A Light in the Attic,51.77,3,In stock,103540.0
1,Tipping the Velvet,53.74,1,In stock,107480.0
2,Soumission,50.10,1,In stock,100200.0
3,Sharp Objects,47.82,4,In stock,95640.0
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,108460.0
...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,1,In stock,111060.0
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,4,In stock,114120.0
997,A Spy's Devotion (The Regency Spies of London #1),16.97,5,In stock,33940.0
998,1st to Die (Women's Murder Club #1),53.98,1,In stock,107960.0
999,"1,000 Places to See Before You Die",26.08,5,In stock,52160.0

In [19]:
# STEP: Categorize books by Price in Naira (₦)
# -------------------------------

# Define bin edges for Naira
# Multiply the previous pound bins by exchange rate (₦2000)
bins_naira = [0, 40000, 80000, 120000, 200000, 400000]  

# Labels for each price range
labels = ["Very Low", "Low", "Medium", "High", "Very High"]

# Create a new column 'Price Range (₦)'
df["Price Range (₦)"] = pd.cut(df["Price (₦)"], bins=bins_naira, labels=labels)

# -------------------------------
# Check the result
# -------------------------------
print(df[["Title", "Price (₦)", "Price Range (₦)"]].head(10))

                                               Title  Price (₦)  \
0                               A Light in the Attic   103540.0
1                                 Tipping the Velvet   107480.0
2                                         Soumission   100200.0
3                                      Sharp Objects    95640.0
4              Sapiens: A Brief History of Humankind   108460.0
5                                    The Requiem Red    45300.0
6  The Dirty Little Secrets of Getting Your Dream...    66680.0
7  The Coming Woman: A Novel Based on the Life of...    35860.0
8  The Boys in the Boat: Nine Americans and Their...    45200.0
9                                    The Black Maria   104300.0

  Price Range (₦)
0          Medium
1          Medium
2          Medium
3          Medium
4          Medium
5             Low
6             Low
7        Very Low
8             Low
9          Medium

In [21]:
# Categorize rating 
df["Rating Group"] = pd.cut(df["Rating"], bins=[0,2,4,5], labels=["Low","Medium","High"])
df

,Title,Price (£),Rating,Availability,Price (₦),Price Range (₦),Rating Group
0,A Light in the Attic,51.77,3,In stock,103540.0,Medium,Medium
1,Tipping the Velvet,53.74,1,In stock,107480.0,Medium,Low
2,Soumission,50.10,1,In stock,100200.0,Medium,Low
3,Sharp Objects,47.82,4,In stock,95640.0,Medium,Medium
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,108460.0,Medium,High
...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,1,In stock,111060.0,Medium,Low
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,4,In stock,114120.0,Medium,Medium
997,A Spy's Devotion (The Regency Spies of London #1),16.97,5,In stock,33940.0,Very Low,High
998,1st to Die (Women's Murder Club #1),53.98,1,In stock,107960.0,Medium,Low
999,"1,000 Places to See Before You Die",26.08,5,In stock,52160.0,Low,High

In [23]:
# Print clean Data
df.to_csv("books_cleaned.csv", index=False)